In [1]:
import pandas as pd
exam = pd.read_csv('exam.csv')

In [2]:
# 앞에서 7줄 출력
exam.head(7)

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65
5   6       2    50       89       98
6   7       2    80       90       45

In [3]:
# 뒤에서 7줄 출력
exam.tail(7)

    id  nclass  math  english  science
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [4]:
# 데이터가 몇행 몇열로 구성되어 있는지 알아보는 명령어
exam.shape

(20, 5)

In [5]:
# 속성일 알아보는 명령어 info
exam.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       20 non-null     int64
 1   nclass   20 non-null     int64
 2   math     20 non-null     int64
 3   english  20 non-null     int64
 4   science  20 non-null     int64
dtypes: int64(5)
memory usage: 928.0 bytes

In [6]:
# mpg 데이터 불러오기
mpg = pd.read_csv('mpg.csv')

In [7]:
mpg.head()

  manufacturer model  displ  year  cyl       trans drv  cty  hwy fl category
0         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
2         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
3         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
4         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [8]:
# 뒷부분 출력 5줄
mpg.tail()

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [14]:
# info 속성확인
# describe 요약

mpg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   manufacturer  234 non-null    object
 1   model         234 non-null    object
 2   displ         234 non-null    float64
 3   year          234 non-null    int64
 4   cyl           234 non-null    int64
 5   trans         234 non-null    object
 6   drv           234 non-null    object
 7   cty           234 non-null    int64
 8   hwy           234 non-null    int64
 9   fl            234 non-null    object
 10  category      234 non-null    object
dtypes: float64(1), int64(4), object(6)
memory usage: 20.2+ KB

In [15]:
mpg.describe()

            displ         year         cyl         cty         hwy
count  234.000000   234.000000  234.000000  234.000000  234.000000
mean     3.471795  2003.500000    5.888889   16.858974   23.440171
std      1.291959     4.509646    1.611534    4.255946    5.954643
min      1.600000  1999.000000    4.000000    9.000000   12.000000
25%      2.400000  1999.000000    4.000000   14.000000   18.000000
50%      3.300000  2003.500000    6.000000   17.000000   24.000000
75%      4.600000  2008.000000    8.000000   19.000000   27.000000
max      7.000000  2008.000000    8.000000   35.000000   44.000000

### 함수와 메서드 차이 알아보기

```
- 내장함수 : 프로그램 안에 미리 정의되어 있는 함수
     sum, max,print,min
- 패키지 함수 : 별도로 설치, 불러와야 하는 함수
     import pandas as pd
     import matplotlib.pyplot as plt
- 메서드 : 변수가 지니고 있는 함수 이름과 괄호 같이 사용
     df.head().info().tail().shape().describe()
     메서드 = 기술 , 어트리뷰트 = 능력치
```

In [16]:
df_raw = pd.DataFrame({'Var1' : [1,2,1],
                      'Var2' : [2,3,2]})
df_raw

   Var1  Var2
0     1     2
1     2     3
2     1     2

In [17]:
df_raw.shape

(3, 2)

In [18]:
# 데이터프레임 복사본 만들기 .copy()
df_new = df_raw.copy()
df_new

   Var1  Var2
0     1     2
1     2     3
2     1     2

In [21]:
# 변수명 바꾸는 메서드 . rename()
df_new = df_new.rename(columns = {'Var2':'v2'})
df_new

   Var1  v2
0     1   2
1     2   3
2     1   2

In [22]:
df_new = df_new.rename(columns = {'Var1':'v1'})
df_new

   v1  v2
0   1   2
1   2   3
2   1   2

In [24]:
print(df_raw)
print(df_new)

   Var1  Var2
0     1     2
1     2     3
2     1     2
   v1  v2
0   1   2
1   2   3
2   1   2

In [25]:
df = pd.DataFrame({'var1':[4,3,8],
                  'var2':[2,6,1]})
df

   var1  var2
0     4     2
1     3     6
2     8     1

In [26]:
df['var_sum'] = df['var1']+df['var2']
df

   var1  var2  var_sum
0     4     2        6
1     3     6        9
2     8     1        9

In [36]:
df['var_mean']= df['var1']+df['var2']+df['var_sum']/2  # var_mean 파생변수 만들기
df

   var1  var2  var_sum  var_mean
0     4     2        6       9.0
1     3     6        9      13.5
2     8     1        9      13.5

In [39]:
# mpg 통합 연비 변수 만들기 연습
mpg['total'] = (mpg['cty']+mpg['hwy'])/2
mpg.head()

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category,total
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact,23.5
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact,25.0
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact,25.5
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact,25.5
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact,21.0

In [40]:
sum(mpg['total'])/ len(mpg)

20.14957264957265

In [41]:
# 평균 .mean()
mpg['total'].mean()

20.14957264957265